# .github/workflows/build.yml
name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Initialize Gradle Wrapper
      run: gradle wrapper --gradle-version=7.5
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: Upload APK artifact (alternative path)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-outputs
        path: app/build/outputs/
